package com.sodyu.lucene.dal.entity;

import java.util.Date;

public class SearchDemoEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.ID
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.spotID
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    private Long spotID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.spotName
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    private String spotName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.ename
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.lat
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.lon
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    private Double lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.address
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.districtName
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    private String districtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.cityName
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.provinceName
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.countryName
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    private String countryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.themeTags
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    private String themeTags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.attentionDegree
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    private Double attentionDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.createTime
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.ID
     *
     * @return the value of demo.ID
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.ID
     *
     * @param ID the value for demo.ID
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.spotID
     *
     * @return the value of demo.spotID
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public Long getSpotID() {
        return spotID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.spotID
     *
     * @param spotID the value for demo.spotID
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public void setSpotID(Long spotID) {
        this.spotID = spotID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.spotName
     *
     * @return the value of demo.spotName
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public String getSpotName() {
        return spotName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.spotName
     *
     * @param spotName the value for demo.spotName
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public void setSpotName(String spotName) {
        this.spotName = spotName == null ? null : spotName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.ename
     *
     * @return the value of demo.ename
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.ename
     *
     * @param ename the value for demo.ename
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.lat
     *
     * @return the value of demo.lat
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.lat
     *
     * @param lat the value for demo.lat
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.lon
     *
     * @return the value of demo.lon
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public Double getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.lon
     *
     * @param lon the value for demo.lon
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public void setLon(Double lon) {
        this.lon = lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.address
     *
     * @return the value of demo.address
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.address
     *
     * @param address the value for demo.address
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.districtName
     *
     * @return the value of demo.districtName
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.districtName
     *
     * @param districtName the value for demo.districtName
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.cityName
     *
     * @return the value of demo.cityName
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.cityName
     *
     * @param cityName the value for demo.cityName
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.provinceName
     *
     * @return the value of demo.provinceName
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.provinceName
     *
     * @param provinceName the value for demo.provinceName
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.countryName
     *
     * @return the value of demo.countryName
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.countryName
     *
     * @param countryName the value for demo.countryName
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName == null ? null : countryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.themeTags
     *
     * @return the value of demo.themeTags
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public String getThemeTags() {
        return themeTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.themeTags
     *
     * @param themeTags the value for demo.themeTags
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public void setThemeTags(String themeTags) {
        this.themeTags = themeTags == null ? null : themeTags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.attentionDegree
     *
     * @return the value of demo.attentionDegree
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public Double getAttentionDegree() {
        return attentionDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.attentionDegree
     *
     * @param attentionDegree the value for demo.attentionDegree
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public void setAttentionDegree(Double attentionDegree) {
        this.attentionDegree = attentionDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.createTime
     *
     * @return the value of demo.createTime
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.createTime
     *
     * @param createTime the value for demo.createTime
     *
     * @mbggenerated Fri Jul 21 11:08:49 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}